apiVersion: v2
appVersion: v1.17.0
description: SMB CSI Driver for Kubernetes
name: csi-driver-smb
version: v1.17.0
dependencies:
  - name: csi-driver-smb
    repository: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    version: v1.17.0
type: application
